---
title: "Functional Variant for BRCA2 Analysis"
author: "Eric Polley"
date: "7/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(rstanarm)
library(lme4)
```

## Load and format data
```{r}
## need to update file name and make sure column and worksheet names match previous versions
dat <- read_excel("../Functional_Prediction/Update081622/updated BRCA2 DBD missense variants for 95%CI and standards re-calibration for Nick_08152022.xlsx", sheet = "Sheet1")
unused_columns <- apply(dat, 2, function(x) sum(is.na(x)) == nrow(dat))
table(table(dat$Uniquevariants))  # any duplicates?

dat <- dat[!(dat$Uniquevariants %in% c("D2723H")), ] # remove D2723H, this is a control/calibration variant, score always = 1

dat2 <- gather(dat[, 1:14], "rep", "score", 2:14)  # 2:14 is because max is 10 replicates, last column was empty, need to check to make sure the right columns are selected
dat2 <- dat2[!is.na(dat2$score), ] # remove the missing values
table(table(dat2$Uniquevariants)) # number of replicates per variant
```

## compute summaries by variant
```{r}
dat_sum <- dat2 %>% group_by(Uniquevariants) %>% summarize(Mean = mean(score), Min = min(score), Max = max(score), N = n(), sd = sd(score)) %>% arrange(Mean)
dat2$Uniquevariants <- factor(dat2$Uniquevariants, ordered = TRUE, levels = dat_sum$Uniquevariants)
```

```{r}
g <- ggplot(dat2, aes(x = score, y = Uniquevariants)) + geom_point() + theme_bw() + geom_point(data = dat_sum, aes(x = Mean, y = Uniquevariants), color = 'red') 
ggsave("../Functional_Prediction/Update081622/all_variants_DBD_Aug2022.pdf", height = 48, width = 12) # write the image to a pdf since too big
```

## estimate a hierarchical Bayesian model
## model on natural log scale
```{r}
dat2$Uniquevariants <- as.character(dat2$Uniquevariants)
dat2$log_score <- log(dat2$score)
fit_log <- stan_glm(log_score ~  -1 + Uniquevariants, data = dat2, family = gaussian, prior = normal(log(3)), chains = 10, iter = 10000)
stan_tbl <- as.data.frame(fit_log$stan_summary)
colnames(stan_tbl) <- paste0("stan_", colnames(stan_tbl))
colnames(stan_tbl) <- gsub("%", "", colnames(stan_tbl))
stan_tbl <- stan_tbl[!(rownames(stan_tbl) %in% c('sigma', 'mean_PPD', 'log-posterior')), ]
stan_tbl$Uniquevariants <- gsub("Uniquevariants", "", rownames(stan_tbl)) # add variant ID
```

```{r}
setdiff(dat_sum$Uniquevariants, stan_tbl$Uniquevariants) # make sure the tables match
setdiff(stan_tbl$Uniquevariants, dat_sum$Uniquevariants)
OUT <- left_join(dat_sum, stan_tbl)
write.csv(OUT, "../Functional_Prediction/Update081622/Stan_model_estimates_DBD_Aug2022.csv") # can update output file name
```

# now add model fit to data plot
```{r}
# order the data again
dat2$Uniquevariants <- factor(dat2$Uniquevariants, ordered = TRUE, levels = dat_sum$Uniquevariants)
OUT$Uniquevariants <- factor(OUT$Uniquevariants, ordered = TRUE, levels = dat_sum$Uniquevariants)
# plot
g <- ggplot(dat2, aes(x = score, y = Uniquevariants)) + geom_point() + theme_bw() +
    geom_point(data = dat_sum, aes(x = Mean, y = Uniquevariants), color = 'red') +
    geom_point(data = OUT, aes(x = exp(stan_mean), y = Uniquevariants), shape = 4, color = 'blue') +
    geom_point(data = OUT, aes(x = exp(stan_10), y = Uniquevariants), shape = 3, color = 'blue') +
    geom_point(data = OUT, aes(x = exp(stan_90), y = Uniquevariants), shape = 3, color = 'blue') +
      geom_point(data = OUT, aes(x = exp(stan_2.5), y = Uniquevariants), shape = 3, color = 'blue') +
    geom_point(data = OUT, aes(x = exp(stan_97.5), y = Uniquevariants), shape = 3, color = 'blue') +
    geom_vline(xintercept = 1.66, linetype = 'dashed') + 
    geom_vline(xintercept = 2.41, linetype = 'dashed')
ggsave("../Functional_Prediction/Update081622/all_variants_with_nl_model_DBD_Aug2022.pdf", height = 48, width = 12) # write the image to a pdf since too big
```

